base_url = "https://victormasson.github.io/"
title = "Hi there ðŸ‘‹"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
title = "Hi there ðŸ‘‹"
links = [
    { title = "GitHub", url = "https://github.com/victormasson", icon = "github" },
    { title = "Twitter", url = "https://twitter.com/vicmassv", icon = "twitter" }
]
projects = [
    { title = "Minsweeper", url = "https://victormasson.github.io/RustTuto/", icon = "land-mine-on" },
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#404256" #"#6FCDBD"
foreground = "#5F74A6" #"#FFF"
hover = "#333"
